'use client'
import { useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { motion } from 'framer-motion'
import Header from './components/header/Header'
import NavBar from './components/navBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const variants = {
  open: {
    x: '24rem'
    // borderRadius: ['50%', '50%', '50%', '10%', '0%']
  },
  closed: {
    x: '4rem'
  }
}

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <html lang='en'>
      <body
        className={inter.className}
        style={{ display: 'flex', overflow: 'hidden' }}
      >
        <Header isOpen={isOpen} setIsOpen={setIsOpen} />
        <NavBar isOpen={isOpen} setIsOpen={setIsOpen} />
        <motion.div
          initial='closed'
          animate={isOpen ? 'open' : 'closed'}
          variants={variants}
          transition={{ duration: 0.5 }}
          style={{
            position: 'absolute',
            width: '100%',
            height: '100%',
            background: 'red'
          }}
        >
          {children}
        </motion.div>
      </body>
    </html>
  )
}
