'use client'
import { useState } from 'react'
import './globals.css'
import { Inter } from 'next/font/google'
import { motion } from 'framer-motion'
import Header from './components/header/Header'
import NavBar from './components/navBar/NavBar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

const variants = {
  open: {
    right: 0,
    top: '50%',
    width: '75%',
    height: '80%',
    transform: 'translateY(-50%) rotateY(-5deg)'

    // borderRadius: ['50%', '50%', '50%', '10%', '0%']
  },
  closed: {
    width: '100%',
    height: '100%'
  }
}

export default function RootLayout({ children }) {
  const [isOpen, setIsOpen] = useState(false)
  return (
    <html lang='en'>
      <body
        className={inter.className}
        style={{
          display: 'flex',
          overflow: 'hidden',
          perspective: '500px',
          background: 'rgb(28, 40, 73)'
        }}
      >
        <Header isOpen={isOpen} setIsOpen={setIsOpen} />
        <NavBar isOpen={isOpen} setIsOpen={setIsOpen} />
        <motion.div
          initial='closed'
          animate={isOpen ? 'open' : 'closed'}
          variants={variants}
          transition={{ duration: 0.3 }}
          style={{
            position: 'absolute',
            marginLeft: '4rem',
            background: 'rgb(20, 29, 53)'
          }}
        >
          {children}
        </motion.div>
      </body>
    </html>
  )
}
